# Generated by Django 5.0.7 on 2024-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0002_message_x_position_message_y_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='message',
            name='x_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='y_position',
            field=models.FloatField(),
        ),
    ]
